services:
  - type: web
    name: asset-api
    runtime: docker
    dockerfilePath: backend/AssetManagement.Api/Dockerfile
    region: oregon
    plan: free
    healthCheckPath: /api/auth/login
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
