services:
  - type: web
    name: asset-api
    runtime: docker
    rootDir: backend/AssetManagement.Api
    region: oregon
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
